language: python
env:
  - DJANGO_VERSION=https://github.com/django/django/archive/stable/3.2.x.zip
python:
  - "3.7"
  - "3.8"
matrix:
  exclude:
    - python: "3.7"
      env: DJANGO_VERSION=https://github.com/django/django/archive/stable/3.2.x.zip
install:
  - pip install $DJANGO_VERSION
  - pip install .
script: ./forms_builder/example_project/manage.py test
